"""add_parent_id_to_category

Revision ID: c648f3ff8a98
Revises: 
Create Date: 2026-05-29 18:21:52.587422

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c648f3ff8a98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'credit_limit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('account', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('budget', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('budget', sa.Column('monthly_limit', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('budget', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('budget', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('budget', sa.Column('is_group_budget', sa.Boolean(), nullable=False))
    op.add_column('budget', sa.Column('is_rollover', sa.Boolean(), nullable=False))
    op.add_column('budget', sa.Column('category_ids_csv', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('budget', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('budget', 'limit_amount')
    op.drop_column('budget', 'year')
    op.drop_column('budget', 'month')
    op.add_column('category', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.alter_column('category', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('category', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.create_foreign_key(None, 'category', 'category', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.alter_column('category', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('category', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('category', 'parent_id')
    op.add_column('budget', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('budget', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('budget', sa.Column('limit_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.alter_column('budget', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('budget', 'category_ids_csv')
    op.drop_column('budget', 'is_rollover')
    op.drop_column('budget', 'is_group_budget')
    op.drop_column('budget', 'end_date')
    op.drop_column('budget', 'start_date')
    op.drop_column('budget', 'monthly_limit')
    op.drop_column('budget', 'name')
    op.alter_column('account', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('account', 'credit_limit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
    # ### end Alembic commands ###
